VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IStrategy"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get costPerKilometer() As Single
End Property

Public Sub Drive(ByVal kilometers As Long)
End Sub

Public Function GetCost(ByVal kilometers As Long)
End Function

