VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISubject"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get SenderMessage() As Range
    
End Property

Public Property Set SenderMessage(ByVal RHS As Range)
    
End Property

Public Sub AttachedUser(ByVal User As IObserver)
    
End Sub

Public Sub NotifyUser()

End Sub
